---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debezium.name" . }}
  labels:
    {{- include "debezium.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.kafka.authentication.username | b64enc }}
  password: {{ .Values.kafka.authentication.password | b64enc }}
  jaas.conf: |
    {{ .Values.kafka.authentication.jaas_conf }}
